name: GH Pages

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Install Node'
        uses: actions/setup-node@v3.6.0

      - name: Install lib dependencies
        run: npm install

      - name: Install docs dependencies
        run: npm install
        working-directory: ./docs

      - name: Copy index
        run: cp index.html 404.html
        working-directory: ./docs

      - name: Build docs
        run: npm run build:prod
        working-directory: ./docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs


